/*

 SPRITE-BLOB.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char blob[] =
{
  0x18,0x18,0x3C,0x3C,0x7E,0x7E,0xFF,0xFF,
  0xFF,0xFF,0x7E,0x7E,0x3C,0x3C,0x18,0x18
};

const unsigned char bg1[] =
{
  0x18,0x18,0x00,0x00,0x00,0x00,0x00,0x00,
  0x18,0x18,0x00,0x00,0x00,0x00,0x00,0x00
};

/* End of SPRITE-BLOB.C */
